export const apiUrls = {
  updateProfile: 'https://discover-inn.com/api/v1/update_profile',
  login: 'https://discover-inn.com/api/v1/login',
  signup: 'https://discover-inn.com/api/v1/register',
  forgotPassword: 'https://discover-inn.com/api/v1/forgot_password',
  changePassword: 'https://discover-inn.com/api/v1/change_password',
  popularAndRated: 'https://discover-inn.com/api/v1/popular_top_rated_maps',
  getCategories: 'https://discover-inn.com/api/v1/categories',
  getTravelType: 'https://discover-inn.com/api/v1/travel_type',
  getBudgetList: 'https://discover-inn.com/api/v1/budget_list',
  getAgeList: 'https://discover-inn.com/api/v1/age_list',
  getCreatedWithin: 'https://discover-inn.com/api/v1/created_within',
  myMaps: 'https://discover-inn.com/api/v1/own_maps',
  tripList: 'https://discover-inn.com/api/v1/trip_list',
  mapList: 'https://discover-inn.com/api/v1/map_list',
  addMyMap: 'https://discover-inn.com/api/v1/add_map',
  addMapPin: 'https://discover-inn.com/api/v1/add_map_pin',
  getMapPins: 'https://discover-inn.com/api/v1/pin_list',
  getMapPinsList: 'https://discover-inn.com/api/v1/map_pin_list',
  deleteReview: 'https://discover-inn.com/api/v1/delete_review',
  editReview: 'https://discover-inn.com/api/v1/update_review',
  updateMapTitle: 'https://discover-inn.com/api/v1/update_map_title',
  updateMapDetails: 'https://discover-inn.com/api/v1/update_map_details',
  updateCoverImage: 'https://discover-inn.com/api/v1/update_map_cover',
  removeMap: 'https://discover-inn.com/api/v1/map_remove',
  addPinFromTripList: 'https://discover-inn.com/api/v1/add_pin_from_trip_list',
  getSinglePin: 'https://discover-inn.com/api/v1/get_single_pin',
  removeSinglePinImage: 'https://discover-inn.com/api/v1/remove_single_pin_image',
  updateMapPin: 'https://discover-inn.com/api/v1/update_map_pin',
  deleteMapPin: 'https://discover-inn.com/api/v1/delete_single_pin',
  deleteFavouriteList: 'https://discover-inn.com/api/v1/delete_favorite_list',
  createFavouriteList: 'https://discover-inn.com/api/v1/create_favorite_list',
  updateFavouriteList: 'https://discover-inn.com/api/v1/update_favorite_list',
  singleFavouritePinList: 'https://discover-inn.com/api/v1/single_favorite_pin_list',
  addRemovePinToFavourite: 'https://discover-inn.com/api/v1/add_remove_pin_to_favourite',
  addReview: 'https://discover-inn.com/api/v1/add_review',
  updateMap: 'https://discover-inn.com/api/v1/update_map',
  visitorReviews: 'https://discover-inn.com/api/v1/visitor_reviews',
  yourReviews: 'https://discover-inn.com/api/v1/your_reviews',
  fetchAllUserNames: 'https://discover-inn.com/api/v1/get_username',
  changeMapStatus: 'https://discover-inn.com/api/v1/change_map_status',
  //remaining
  sharedMapsList: 'https://discover-inn.com/api/v1/shared_maps_list',
  shareMap: 'https://discover-inn.com/api/v1/shared_your_map',
  searchUsers: 'https://discover-inn.com/api/v1/search_users',
  searchUserMaps: 'https://discover-inn.com/api/v1/search_users_maplist',
  singleMapReview:'https://discover-inn.com/api/v1/single_map_review',
  setPassword:'https://discover-inn.com/api/v1/set_new_password',
  update_favorite_pin_list_order:'https://discover-inn.com/api/v1/update_favorite_pin_list_order',
  deleteAccount : 'https://discover-inn.com/api/v1/remove_user'
};
