import {Dimensions, StyleSheet} from 'react-native';
const DEVICE_HEIGHT = Dimensions.get('window').height;
const DEVICE_WIDTH = Dimensions.get('window').width;
export default StyleSheet.create({
  page: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 25,
  },
  map: {
    flex: 1,
  },
  pinScrollView: {
    paddingTop: 0,
    height: DEVICE_HEIGHT - 320,
    width: DEVICE_WIDTH,
    backgroundColor: 'white',
    borderRadius: 20,
    marginBottom: 20,
    marginTop: 340,
  },
  pinViewTitle: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 24,
    marginBottom: 5,
    paddingLeft: 15,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  pinViewCate: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 10,
    alignSelf: 'flex-start',
    paddingLeft: 15,
  },
  pinViewCateIcon: {
    color: '#2F80ED',
    fontSize: 13,
  },
  pinViewCateText: {
    fontSize: 12,
    color: '#828282',
    fontFamily: 'Montserrat-Regular',
  },
  pinViewContent: {
    fontSize: 12,
    fontFamily: 'Montserrat-Medium',
    color: '#4F4F4F',
    paddingHorizontal: 15,
  },
  pinHeader: {
    zIndex: 9999,
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    height: 60,
    paddingHorizontal: 20,
    width: '100%',
  },
  cateSlideCard: {
    height: 375,
    marginBottom: 10,
    shadowOffset: {width: 0, height: 5},
    shadowColor: 'rgba(6, 18, 42, 0.08);',
    shadowOpacity: 1.0,
    backgroundColor: '#fff',
    alignItems: 'flex-start',
    justifyContent: 'center',
    textAlign: 'center',
    borderRadius: 5,
  },
  cateSlideCardIcon: {
    height: 450,
    width: DEVICE_WIDTH,
    alignSelf: 'center',
    top: 0,
    position: 'absolute',
  },
  cateSlideCardTitle: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 10,
    lineHeight: 12,
    marginTop: 10,
    color: '#333333',
    textAlign: 'center',
  },
  orDivider: {
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    flex: 1,
    marginVertical: 20,
    marginHorizontal: 15,
  },
  orDividerText: {
    fontSize: 14,
    fontFamily: 'Montserrat-Regular',
    color: '#333333',
    paddingHorizontal: 10,
    zIndex: 7,
    backgroundColor: '#ffffff',
  },
  orDividerBorder: {
    position: 'absolute',
    width: '100%',
    height: 1,
    zIndex: 6,
    backgroundColor: '#C4C4C4',
  },
  button: {
    paddingVertical: 5,
    paddingHorizontal: 30,
    height: 40,
    alignSelf: 'center',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonPrimary: {
    backgroundColor: '#2F80ED',
  },
  buttonReview: {
    marginTop: 15,
  },
  buttonText: {
    color: '#fff',
    fontSize: 12,
    fontFamily: 'Montserrat-Medium',
  },
  customPopup: {
    width: DEVICE_WIDTH,
    padding: 0,
    position: 'absolute',
    bottom: 0,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#ccc',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: {width: 0, height: -2},
    shadowRadius: 10,
    maxHeight: DEVICE_HEIGHT - 100,
    overflow: 'scroll',
  },
  customPopupContent: {
    paddingVertical: 20,
    paddingHorizontal: 5,
  },
  customPopupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  customPopupHeaderTitle: {
    fontSize: 16,
    fontFamily: 'Montserrat-SemiBold',
    color: '#333333',
  },
  buttonClose: {
    width: 24,
    height: 24,
  },
  buttonCloseIcon: {
    color: '#BDBDBD',
    fontSize: 24,
  },
  formGroup: {
    marginBottom: 15,
  },
  formLabel: {
    color: '#4F4F4F',
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 5,
    paddingLeft: 7,
  },
  formControl: {
    borderWidth: 1,
    borderColor: '#BDBDBD',
    borderRadius: 5,
    height: 48,
    paddingLeft: 25,
    paddingRight: 25,
    fontFamily: 'Montserrat-Medium',
    color: '#4F4F4F',
    fontSize: 14,
  },
  buttonCTGroup: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  buttonCT: {
    flex: 1,
  },
  buttonCTCancel: {
    marginRight: 10,
  },
  buttonCTSubmit: {
    marginLeft: 10,
  },
  buttonOutline: {
    borderColor: '#BDBDBD',
    borderWidth: 1,
    color: '#fff',
  },
  buttonTextDark: {
    color: '#333333',
  },
  mapViewCard: {
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: DEVICE_WIDTH - 40,
    flexDirection: 'row',
    elevation: 3,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: 'rgba(242, 242, 242, 0.5)',
  },
  mapViewCardImg: {
    width: 120,
    height: 95,
  },
  mapViewCardContent: {
    width: DEVICE_WIDTH - 120,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  mapViewTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: DEVICE_WIDTH - 20,
  },
  mapViewTitleText: {
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    fontWeight: '500',
  },
  mapViewCate: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 5,
  },
  mapViewCateIcon: {
    color: '#2F80ED',
    fontSize: 13,
  },
  mapViewCateText: {
    fontSize: 12,
    color: '#828282',
    fontFamily: 'Montserrat-Regular',
  },
  mapViewContentText: {
    fontSize: 12,
    fontFamily: 'Montserrat-Regular',
    color: '#828282',
  },
  MVTripList: {
    marginBottom: 20,
    maxHeight: 100,
  },
  MVTripListItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderBottomColor: '#F2F2F2',
    borderBottomWidth: 1,
  },
  MVTripListItemTitle: {
    color: '#BDBDBD',
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
  },
});
